title: kxddah.misconf
email:
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kxddahmisconf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Kxddah
github_username:  kxddahmisconf

plugins:
  - jekyll-feed

theme: jekyll-dash

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# for github pages custom domains:
# include: [CNAME]

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: local
  #github_username: bitbrain
  #avatar_source: local
  #avatar_path:

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/Kxddah
      icon: twitter-square
      color: cyan
    - url: https://www.linkedin.com/in/hardik-singh-b875a5216/
      icon: linkedin
      color: blue
    - url: https://github.com/kxddahmisconf
      icon: github-square
      color: purple
    - url: https://hackerone.com/kiddah
      icon: hackerone-square
      color: teal
    - url: https://bugcrowd.com/kiddah
      icon: bugcrowd
      color: orange
  
  # wether the author box should be displayed or not
  show_author: true
